### ISSUE TITLE
Добавить ссылку на получение OAuth токена в настройки ноды

### ISSUE THREAD

**Issue by ptath** [twocolors/node-red-contrib-alice-self-hosting#1]
Сложно понять где взять токен, предлагаю добавить ссылку на страницу получения где-нибудь тут

<img width="506" alt="Снимок экрана 2023-12-20 в 00 20 38" src="https://github.com/twocolors/node-red-contrib-alice-self-hosting/assets/397799/dbbc067d-d5c9-4989-a884-f725fe9328ba">

**Comment by twocolors** [comment]
Можно добавить ниже где информация о **deploy** или оставить в разделе help как сейчас

**Comment by ptath** [comment]
хелп для нубов, у профи там всегда открыт дебаг =) мне кажется ссылку на получение токена надо разместить как можно ближе к полю "OAuth Token", а еще лучше над ним

кстати и на получение "skill id" тоже ссылку можно дать

и самое главное — показать в полях (placeholder) не "Skill Id", "OAuth Token" итп, а прям "aaaaaaa-bbbbb-cccc-ddddddddddd" и "y0_aAaAaAaAHaAhsAsas-zZzZ", чтоб юзер видел как оно должно выглядеть и не плодил ишшуи

**Comment by twocolors** [comment]
Исправил, будет в ноом релизе
