### ISSUE TITLE
Validation error when port field is empty

### ISSUE THREAD

**Issue by alvlapo** [twocolors/node-red-contrib-alice-self-hosting#17]
An empty field or port number less than 4 characters long is validated with an error, I hide behind a reverse proxy and do not use the port to connect over https.

Everything works well, except for the warning when nodes are deployed.

![Снимок экрана 2024-03-06 в 20 24 02](https://github.com/twocolors/node-red-contrib-alice-self-hosting/assets/551744/faf4c5e2-574a-4fc8-b688-7f73ce154729)

NodeRed 3.1.6
node-red-contrib-alice-self-hosting 0.1.5

**Comment by twocolors** [comment]
@alvlapo you can enter default ports 1880 and not be error

**Comment by alvlapo** [comment]
@twocolors I use reverse proxying on my domain, like https://alice.mydomail.com/2j55kkl45/webhook,  if I specify port 443, but a validation error happens to it as well. I see that the field is mandatory, numeric in the range 1024 to 60000, and it seems strange to me.

**Comment by twocolors** [comment]
@alvlapo welcome to https://t.me/alice_in_red_wonderland for discussion about this

i think this will faster

**Comment by alvlapo** [comment]
Sorry, my bad

**Comment by twocolors** [comment]
With your task, an error was discovered that you need to check ports less than 1024 (if Node-RED use port 443).

I'll open it and close it when I add a fix.
