### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Meduzjam** [twocolors/node-red-contrib-alice-self-hosting#7]
Видео с камеры не передается. В ответе на умение Video_stream нет объекта:
```
"value": {
                "stream_url": "https://host/path/to/playlist.m3u8?token=123456789abcdef",
                "protocol": "hls"
              },
```
вот что видно в Логе запросов Яндекса

`{"request_id":"f03197c5-8db1-48df-9183-fae6df502adf","payload":{"user_id":"a8b51703bd65dce9","devices":[{"id":"1358de62c2236539","capabilities":[{"type":"devices.capabilities.video_stream","state":{"instance":"get_stream","action_result":{"status":"DONE"}}}]}]}}`

**Comment by twocolors** [comment]
Привет, удивлен что кто-то использует видео (: 

Попробуйте
node-red-contrib-alice-self-hosting@0.1.2
